### ISSUE TITLE
Example code mentioned in book preface is missing

### ISSUE THREAD

**Issue by jdavcs** [PacktPublishing/PostgreSQL-14-Administration-Cookbook#1]
The Preface (p. xxiv) mentions example code files and provides a link to this location. Could you, please, make them available? Thank you!

**Comment by jmilbery** [comment]
Same -- when are you releasing the example code files?

**Comment by JosephA-packt** [comment]
Sorry to tell you this @jdavcs and @jmilbery we do not have any code files for this title and the code is referenced in each individual chapter.
